
# The purpose of the .dev on the end right there is gonna make sure
# that it's really clear that this Dockerfile is only used
# when we are trying to run our application in a development environment.

FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm","run","start"]

